# Generated by Django 2.2.7 on 2023-06-20 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveymessage',
            name='country_name',
        ),
        migrations.AddField(
            model_name='surveymessage',
            name='notes',
            field=models.TextField(default=django.utils.timezone.now, max_length=1500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveymessage',
            name='country',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='国家名称'),
        ),
        migrations.AlterField(
            model_name='surveymessage',
            name='date',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='surveymessage',
            name='introduction',
            field=models.CharField(max_length=128, null=True, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='surveymessage',
            name='platform',
            field=models.CharField(choices=[('1', 'AMD'), ('2', 'ACA'), ('3', 'AIN'), ('4', 'BCA'), ('5', 'ALP'), ('6', 'APN')], max_length=1, verbose_name='平台'),
        ),
    ]
